public with sharing class collectionfirst {
    private String title;
    Private Integer price;
    private String author;
    
    Public CollectionFirst(){
        title = 'SFDC ';
        price = 200;
        author = 'Sandeep';
    }
    
    Public string gettitle(){
         return title;   
    }
    
    Public Integer getprice(){
         return price;
    }
    
    Public String getauthor(){
         return author;
    }
}