public class Testheight{
    public static testMethod void main(){
        // For Default Constructor
        
        Height Men = new Height();
        Men.SetValue(3,6);
        Men.GetValue();
        
        
        // Parameterised Constructor
        Height Man1 = new Height(5);
        Man1.getvalue();
        
        Height Man2 = new Height();
        Man2.Setvalue(6);
        Man2.Getvalue();
    }

}